# Postgres connection
spring.datasource.url=jdbc:postgresql://localhost:5432/wurdal
spring.datasource.username=962586
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml